Initial implementation of Nightscout service
tidepool-org/NightscoutService pull request #2
Opened 2019-09-24 05:18 UTC by darinkrauss

- Implement Service and ServiceUI protocols
- Implement RemoteData protocol
- Connect with Nightscout third-party service

https://tidepool.atlassian.net/browse/LOOP-22

2019-09-24 18:35 UTC, nhamming submitted a review, later dismissed
LGTM

2019-09-30 16:57 UTC, nhamming submitted a review, later dismissed
+1

2019-10-03 12:09 UTC, nhamming submitted a review, later dismissed
+1

2019-10-04 19:19 UTC, ps2 approved these changes
Looks great!

2019-10-04 19:19 UTC, ps2 commented on Common/LocalizedString.swift
> +//  Copyright © 2019 LoopKit Authors. All rights reserved.
Thanks for setting up the Copyright as LoopKit Authors for this. 👍

2019-10-04 20:29 UTC, ps2 requested changes
Looks great!

2019-10-04 20:29 UTC, ps2 commented on NightscoutServiceKitUI/NightscoutServiceTableViewController.swift
> +            message: NSLocalizedString("Are you sure you want to delete this service?", comment: "Confirmation message for deleting a service"),
NSLocalizedString -> LocalizedString

2019-10-05 16:53 UTC, ps2 approved these changes
🎉 LGTM!

2019-10-07 16:19 UTC, merged